apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Maven pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Maven build
        uses: docker://maven:3-eclipse-temurin-17
        shell: sh
        run: |
          mvn clean verify -Dtest="*,!MySql*,!Postgres*"
  SonarQube:
    steps:
      - uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v1
        name: Run SonarQube scan
        kind: scan
      - uses: cloudbees-io/jfrog-artifactory-upload-file@v1
        kind: deploy
        with:
          url: https://mycbplatform.jfrog.io/artifactory/libs-release
          token: cmVmdGtuOjAxOjE3MzEwMDk0ODM6TFRLUFJwN0tEUTNPcnlOWUtMU2Vjb25yWlJs
          file-path: /System/Volumes/Data/Users/lgaudet/workspace/spring-petclinic
          artifactory-path: libs-release/
    needs:
      - build
