apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Petclinic pipeline

on:
  push:
    branches:
      - main

jobs:
  checkout:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
  build:
    steps:
      - name: List
        uses: docker://maven:3-eclipse-temurin-17
        shell: sh
        run: |
          ls -l
      - name: Maven build
        uses: docker://maven:3-eclipse-temurin-17
        shell: sh
        run: |
          mvn clean verify -Dtest="*,!MySql*,!Postgres*"
