apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Petclinic pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1
      - name: Maven build
        uses: docker://maven:3-eclipse-temurin-17
        shell: sh
        run: |
          mvn clean verify -Dtest="*,!MySql*,!Postgres*"
      - name: SonarQube
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v1
        kind: scan
  deploy:
    steps:
      - uses: cloudbees-io/s3-upload-object@v1
        kind: deploy
        with:
          bucket-name: myplatformbucket
          file-path: /users/lgaudet/myapp.tar.gz
          s3-path: /myplatformbucket?region=us-east-2
    needs:
      - build
